### ISSUE TITLE
keybox use cpu 1 only one core

### ISSUE THREAD

**Issue by voravitl** [skavanagh/KeyBox#182]
Hi
I have problem with keybox . when I saw  audit log  keybox it use cpu just only 1 core and so slow  query  . but my server it have 4 core cpu . Can u help me or tall me if you have any config from java it can use Multi cpu

**Comment by skavanagh** [comment]
well a single DB query shouldn't span multiple cores, but here is a jetty guide on high-load configurations

http://www.eclipse.org/jetty/documentation/current/high-load.html

The audit in keybox has issues if the size of the data is too large . You can configure a logging utility for this data. There is an example on how to configure commented out.
https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/log4j2.xml#L16-L28

Another thing to consider would be to run the DB in mixed-mode or server mode (rather than embedded)

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/KeyBoxConfig.properties#L54

change
```
dbConnectionURL=jdbc:h2:keydb/keybox;CIPHER=AES;
```
to either
```
dbConnectionURL=jdbc:h2:keydb/keybox;CIPHER=AES;AUTO_SERVER=TRUE
```
or
```
dbConnectionURL=jdbc:h2:tcp://<host>:<port>/~/keybox;CIPHER=AES;
```

**Comment by voravitl** [comment]
Thank you for help 
it look like better  but audit in keybox . I  mean audit session not audit auth  because from your provide config it look like audit log auth not audit session  and if u have any config please ask me 

Thank you so much

**Comment by voravitl** [comment]
hi 

it still use one core when i delete old server 

this is error log 

2016-12-20 02:21:33.917:WARN:oejwja.JsrEvents:qtp110718392-17: Unable to report throwable to websocket (no @OnError handler declared): com.keybox.manage.socket.SecureShellWS
java.lang.NullPointerException
        at com.keybox.common.util.AuthUtil.getSessionId(AuthUtil.java:116)
        at com.keybox.manage.socket.SecureShellWS.onOpen(SecureShellWS.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71)
        at org.eclipse.jetty.websocket.jsr356.annotations.OnOpenCallable.call(OnOpenCallable.java:54)
        at org.eclipse.jetty.websocket.jsr356.annotations.JsrEvents.callOpen(JsrEvents.java:170)
        at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onConnect(JsrAnnotatedEventDriver.java:187)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:229)
        at org.eclipse.jetty.websocket.jsr356.endpoints.AbstractJsrEventDriver.openSession(AbstractJsrEventDriver.java:104)
        at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:503)
        at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:432)
        at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:198)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onOpen(AbstractWebSocketConnection.java:566)
        at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:200)
        at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:375)
        at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:640)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:454)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
