### ISSUE TITLE
KeyBox v2.88.00 Upgrade - java.lang.NoClassDefFoundError: org/eclipse/jetty/client/HttpClient

### ISSUE THREAD

**Issue by colandre** [skavanagh/KeyBox#196]
Hello @skavanagh,
thanks for your hard work. I apreciate much.

I tried to upgrade my Keybox installation from version 2.87.01 to 2.88.00.
(I already upgraded Keybox many times).

This time while starting it, I receive a NoClassDefFoundError exception.
Here below some rows, the full stack trace is in a pastebin link here below.
```
2017-01-14 13:28:11.711:WARN:oejd.DeploymentManager:main: Unable to reach node goal: started
java.lang.NoClassDefFoundError: org/eclipse/jetty/client/HttpClient
        at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:263)
        at org.eclipse.jetty.websocket.jsr356.ClientContainer.<init>(ClientContainer.java:108)
        at org.eclipse.jetty.websocket.jsr356.server.ServerContainer.<init>(ServerContainer.java:56)
        at org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer.configureContext(WebSocketServerContainerInitializer.java:139)
```

Full stack trace here: http://pastebin.com/ZgnhNWwb

What am I doing wrong?

Thanks
Andrea

**Comment by skavanagh** [comment]
you need to add
```
--module=client
```
to your jetty/start.ini file.  I think it was enabled by default prior to 9.4.0.

**Comment by colandre** [comment]
Thank you @skavanagh,

my fault. I copied the entire start.ini from previous version (2.87.01) due to a change I added in order to configure jetty to listen just on localhost and accepting connections just from the local apache in front of it. (jetty.host=127.0.0.1)

I thought it would work.
Sorry.

It works now. Thank you

**Comment by skavanagh** [comment]
Yeah! I had it happen to me too when putting the release together :smile:
