### ISSUE TITLE
LDAP users have no profile; can we just populate them? 

### ISSUE THREAD

**Issue by louisdj** [skavanagh/KeyBox#216]
Hi

We are testing KeyBox in combination with active directory. We are letting users upload their own key to KeyBox.
On their first login, they get an error because there is no profile assigned to them, which creates a lot of overhead if they need to login, after that IT has to login and assign them, after which the user has to login again to add his key.

Could it be possible to just populate all the users out of AD (in the future maybe just decide based on their OU)?

If an employee is disabled or removed in AD, their keys should also be automatically removed from KeyBox in my opinion, is this also possible?

**Comment by skavanagh** [comment]
> Could it be possible to just populate all the users out of AD (in the future maybe just decide based on their OU)?

This is something that I want too. Discussed it some here https://github.com/skavanagh/KeyBox/issues/17#issuecomment-203377380 ..but having the user's LDAP groups match on profile names in KeyBox and set the user profiles as they login.  This will be the next thing I work on (I've been putting it off for a while now).

> If an employee is disabled or removed in AD, their keys should also be automatically removed from KeyBox in my opinion, is this also possible?

That's a little tougher.. You could always write something to delete the user out of the H2 database when revocation happens in AD.  It will cascade, delete the user's keys as well, and remove them from the systems.

**Comment by louisdj** [comment]
Hi
Thank you for the update; looking forward to the new functionality.
For the deletion of users I will check how we will handle it, because we are using a docker(-ised) version.

**Comment by skavanagh** [comment]
Added new JAAS example on how to configure this - https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/jaas.conf#L28-L49

**Comment by louisdj** [comment]
Which parameter should be given to the jaasModule setting? Is it just ldap-ol or ldap-ol-with-roles?

**Comment by skavanagh** [comment]
ldap-ol-with-roles -  the module allows you to specify an LDAP admin to bind, so it can lookup user roles.

**Comment by louisdj** [comment]
Ok, I will look further in my jaas.conf then, because login is not possible. It's also not possible to login with the local admin, but I'm not sure if that is possible when ldap is enabled.

**Comment by louisdj** [comment]
@skavanagh If the jaas.conf file is configured correctly, should there be anything else configured to be able to login with an AD account? 
I've token the configuration from other applications where login is working but for Keybox I always receive:
`INFO  LoginAudit - louis.dejaeger (172.17.0.1) - Authentication Failed : Login credentials are invalid`

**Comment by skavanagh** [comment]
you can set this flag to 'true' https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/jaas.conf#L31
to see what's going on.

**Comment by louisdj** [comment]
It is on, but not seeing any additional logs.... Only the line above....

**Comment by skavanagh** [comment]
Ok.  You should also be able to see what exception is being raised when the login fails by setting this to 'debug' .  It may provide more info.

https://github.com/skavanagh/KeyBox/blob/master/src/main/resources/log4j2.xml#L32

**Comment by louisdj** [comment]
Could this be the issue?

```
2017-06-26 05:47:33,942 DEBUG ExternalAuthUtil - javax.security.auth.login.LoginException: unable to find LoginModule class: org.eclipse.jetty.jaas.spi.LdapLoginModule
javax.security.auth.login.LoginException: unable to find LoginModule class: org.eclipse.jetty.jaas.spi.LdapLoginModule
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:794) ~[?:1.8.0_111-internal]
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_111-internal]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_111-internal]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_111-internal]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111-internal]
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_111-internal]
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_111-internal]
	at com.keybox.manage.util.ExternalAuthUtil.login(ExternalAuthUtil.java:112) [classes/:?]
	at com.keybox.manage.db.AuthDB.login(AuthDB.java:50) [classes/:?]
	at com.keybox.manage.action.LoginAction.loginSubmit(LoginAction.java:86) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111-internal]
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:873) [ognl-3.1.12.jar:?]
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1539) [ognl-3.1.12.jar:?]
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) [ognl-3.1.12.jar:?]
	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:96) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:88) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1615) [ognl-3.1.12.jar:?]
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91) [ognl-3.1.12.jar:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) [ognl-3.1.12.jar:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) [ognl-3.1.12.jar:?]
	at ognl.Ognl.getValue(Ognl.java:467) [ognl-3.1.12.jar:?]
	at ognl.Ognl.getValue(Ognl.java:431) [ognl-3.1.12.jar:?]
	at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:351) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:403) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:349) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:436) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:291) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:252) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:253) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:177) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:260) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:73) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:139) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:133) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:133) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:192) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:69) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:115) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:88) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:246) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:99) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:139) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:155) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:174) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:120) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:171) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:195) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:193) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.keybox.common.interceptor.ClickjackingInterceptor.intercept(ClickjackingInterceptor.java:45) [classes/:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.keybox.common.interceptor.HTTPStrictTransportSecurityInterceptor.intercept(HTTPStrictTransportSecurityInterceptor.java:46) [classes/:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.interceptor.TokenInterceptor.handleValidToken(TokenInterceptor.java:193) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.keybox.common.interceptor.CSRFInterceptor.handleToken(CSRFInterceptor.java:54) [classes/:?]
	at org.apache.struts2.interceptor.TokenInterceptor.doIntercept(TokenInterceptor.java:141) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:54) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:81) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:143) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629) [jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:278) [jetty-io-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:148) [jetty-io-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```

**Comment by skavanagh** [comment]
Yes it's missing this jar -https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-jaas/9.4.5.v20170502

which is strange b/c it's there when it's build from source.

**Comment by skavanagh** [comment]
Found the issue.. Add this
```
--module=jaas
```
 to the jetty/start.ini file. Then the jar should be added to the server's classpath.

**Comment by louisdj** [comment]
Is there a way to test the jaas.conf configuration? I configured everything (just with Jetty on Ubuntu, no docker), but still getting the error the 'Login credentials are invalid'.

**Comment by skavanagh** [comment]
Outside of setting the debug flag, not really! You can use an LDAP client like directory studio http://directory.apache.org/studio/ and try out the credentials.

**Comment by louisdj** [comment]
Credentials are working, I also checked the OU mappings, but they seem correct... Still getting the message "user not found".

```
ldap-ol-with-roles {
    //openldap auth with roles that can map to profiles
    org.eclipse.jetty.jaas.spi.LdapLoginModule required
    debug="true"
    useLdaps="false"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    hostname="itpagency.be"
    port="389"
    bindDn="CN=***,OU=Active Directory,OU=Service Accounts,DC=itpagency,DC=be"
    bindPassword="************"
    authenticationMethod="simple"
    forceBindingLogin="false"
    userBaseDn="DC=itpagency,DC=be"
    userRdnAttribute="uid"
    userIdAttribute="uid"
    userPasswordAttribute="userPassword"
    userObjectClass="inetOrgPerson"
    roleBaseDn="OU=ITP Groups,OU=Groups,DC=itpagency,DC=be"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="groupOfNames";
};
```

**Comment by skavanagh** [comment]
Not sure since everyone's ldap is different. .. but your 'userBaseDN' seems off.  Is it missing an OU=<something>?

**Comment by louisdj** [comment]
Yeah, sorry the userBaseDN is OU=ITP Employees,DC=itpagency,DC=be (I removed the OU to test if it worked without, but it did not)...

**Comment by skavanagh** [comment]
Ok - so it should be looking for the user as - 'uid=\<someuser\>,OU=ITP Employees,DC=itpagency,DC=be' Does logging in with the LDAP client using the bindDN to lookup that user work?  Sometimes it helps to look at the ldap server logs too.
