### ISSUE TITLE
Upgrade failed 2_88.02 -> 2_89.00

### ISSUE THREAD

**Issue by Calyrx** [skavanagh/KeyBox#229]
When I Use the Upgradetool with:
java -jar 2_89-upgrade.jar /opt/KeyBox/jetty/keybox/WEB-INF/classes/KeyBoxConfig.properties 
Upgrade successful

the Keybox start and throw a error after the first login:
`2017-05-29 13:25:41.894:INFO::main: Logging initialized @827ms to org.eclipse.jetty.util.log.StdErrLog
2017-05-29 13:25:42.278:INFO:oejs.Server:main: jetty-9.4.2.v20170220
2017-05-29 13:25:42.302:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/KeyBox/jetty/webapps/] at interval 1
2017-05-29 13:25:44.804:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=2049ms
2017-05-29 13:25:45.357:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-05-29 13:25:45.357:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-05-29 13:25:45.358:INFO:oejs.session:main: Scavenging every 660000ms
2017-05-29 13:25:49.000:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5ec0a365{/,file:///opt/KeyBox/jetty/keybox/,AVAILABLE}{/opt/KeyBox/jetty/keybox}
2017-05-29 13:25:49.039:INFO:oejus.SslContextFactory:main: x509=X509@31be6b49(jetty,h=[],w=[]) for SslContextFactory@2e16b08d(file:///opt/KeyBox/jetty/etc/keystore,file:///opt/KeyBox/jetty/etc/keystore)
2017-05-29 13:25:49.047:INFO:oejs.AbstractConnector:main: Started ServerConnector@42561fba{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2017-05-29 13:25:49.047:INFO:oejs.Server:main: Started @7981ms
2017-05-29 13:26:07,554 ERROR AuthDB - org.h2.jdbc.JdbcSQLException: Feld "ENABLED" nicht gefunden
Column "ENABLED" not found; SQL statement:
select salt from users where enabled=true and username=? [42122-194]
org.h2.jdbc.JdbcSQLException: Feld "ENABLED" nicht gefunden
Column "ENABLED" not found; SQL statement:
select salt from users where enabled=true and username=? [42122-194]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.194.jar:1.4.194]
...
`

- I have checked the user-rights

- About this Installation:
CentOS Linux release 7.3.1611 (Core) 
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

- This error also occurs on another, independent server

Can you help me?

**Comment by skavanagh** [comment]
Looks like you maybe running the new updated DB off the old code base.

I would try and download 2.89 again and copy the
KeyBoxConfig.properties, keybox.jceks, jaas.conf, log4j2.xml (in the WEB-INF/classes)
id_rsa.pub , keybox.mv.db (in the WEB-INF/classes/keydb)
to the 2.89 installation

**Comment by Calyrx** [comment]
Thank you. This works for me :-)

**Comment by Calyrx** [comment]
After the new installation I can login. But the function of ssh-termes failed:

`2017-06-01 09:29:14.924:INFO::main: Logging initialized @2405ms to org.eclipse.jetty.util.log.StdErrLog
2017-06-01 09:29:16.287:INFO:oejs.Server:main: jetty-9.4.2.v20170220
2017-06-01 09:29:16.421:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/KeyBox/jetty/webapps/] at interval 1
2017-06-01 09:29:22.782:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=5098ms
2017-06-01 09:29:24.200:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2017-06-01 09:29:24.201:INFO:oejs.session:main: No SessionScavenger set, using defaults
2017-06-01 09:29:24.205:INFO:oejs.session:main: Scavenging every 660000ms
channel 7: open failed: connect failed: Connection refused
channel 7: open failed: connect failed: Connection refused
2017-06-01 09:29:35.278:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5ec0a365{/,file:///opt/KeyBox/jetty/keybox/,AVAILABLE}{/opt/KeyBox/jetty/keybox}
2017-06-01 09:29:35.344:INFO:oejus.SslContextFactory:main: x509=X509@31be6b49(jetty,h=[],w=[]) for SslContextFactory@2e16b08d(file:///opt/KeyBox/jetty/etc/keystore,file:///opt/KeyBox/jetty/etc/keystore)
2017-06-01 09:29:35.375:INFO:oejs.AbstractConnector:main: Started ServerConnector@42561fba{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2017-06-01 09:29:35.385:INFO:oejs.Server:main: Started @22866ms
2017-06-01 09:29:51,656 INFO  LoginAudit - admin (10.0.7.28) - Authentication Success
2017-06-01 09:30:04,678 ERROR SessionAuditDB - org.h2.jdbc.JdbcSQLException: Feld "FIRST_NM" nicht gefunden
Column "FIRST_NM" not found; SQL statement:
insert into session_log (first_nm, last_nm, username) values(?,?,?) [42122-194]
org.h2.jdbc.JdbcSQLException: Feld "FIRST_NM" nicht gefunden
Column "FIRST_NM" not found; SQL statement:
insert into session_log (first_nm, last_nm, username) values(?,?,?) [42122-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.table.Table.getColumn(Table.java:676) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.command.Parser.parseColumn(Parser.java:880) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.command.Parser.parseColumnList(Parser.java:864) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.command.Parser.parseInsert(Parser.java:1064) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.command.Parser.parsePrepared(Parser.java:415) ~[h2-1.4.194.jar:1.4.194]`

**Comment by skavanagh** [comment]
ok - now try and download 

https://github.com/skavanagh/KeyBox/releases/download/v2.89.00/2_89-upgrade.jar

and rerun 
```
java -jar keybox-upgrade-2_89.jar <whatever path>/jetty/keybox/WEB-INF/classes/KeyBoxConfig.properties
```
on the new installation

**Comment by Calyrx** [comment]
Thank you! This works for me :-)
