### ISSUE TITLE
Migrating from 2.85.01

### ISSUE THREAD

**Issue by absane** [skavanagh/KeyBox#231]
I'm having a fairly difficult time trying to migrate from 2.85.01 to the latest, or at least a close-to-latest version. I cannot tell if I need to upgrade from 2.85.01 to minor versions or if I can go straight to the latest. In addition, the Upgrade JAR I am trying to use keeps starting following:

`org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.validateUserAndPassword(Engine.java:336)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:162)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.keybox.manage.util.DBUtils.getConn(DBUtils.java:60)
	at Upgrade.main(Upgrade.java:19)
`

Thing is, I never recall configuring credentials. Maybe I did, but I do not know where to find these.

Is there an easy(ier) way to go to the latest?

Thanks!

**Comment by skavanagh** [comment]
There should be two upgrade jars you need to run coming from 2.85. The params are a little different so make note and they need to be run in the order below.  The first jar will have you set a password for the DB.

https://github.com/skavanagh/KeyBox/releases/download/v2.87.00/keybox-upgrade-2_87.jar
```
java -jar keybox-upgrade-2_87.jar <whatever path to DB in new installation>/keybox.h2.db
```
https://github.com/skavanagh/KeyBox/releases/download/v2.89.00/keybox-upgrade-2_89.jar
```
java -jar keybox-upgrade-2_89.jar <whatever path>/jetty/keybox/WEB-INF/classes/KeyBoxConfig.properties
```

**Comment by skavanagh** [comment]
also, you need to make sure these two properties have been added in your KeyBoxConfig.properties file.
```
#The session time out value of application in minutes
sessionTimeout=15
#Requires JDK with "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files" installed - http://www.oracle.com/technetwork/java/javase/downloads/index.html
use256EncryptionKey=false
```
