### ISSUE TITLE
Error thrown while starting KeyBox

### ISSUE THREAD

**Issue by varshithr** [skavanagh/KeyBox#237]
```2017-07-19 10:17:14,483 ERROR DefaultClassFinder - Unable to read class [com.keybox.manage.action.SecureShellAction]
com.opensymphony.xwork2.XWorkException: Could not load java/lang/Object.class
	at org.apache.struts2.convention.DefaultClassFinder.readClassDef(DefaultClassFinder.java:462) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.DefaultClassFinder.access$200(DefaultClassFinder.java:49) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.DefaultClassFinder$InfoBuildingVisitor.extractSuperInterfaces(DefaultClassFinder.java:511) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.DefaultClassFinder$InfoBuildingVisitor.visit(DefaultClassFinder.java:498) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.1.jar:5.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.1.jar:5.1]
	at org.apache.struts2.convention.DefaultClassFinder.readClassDef(DefaultClassFinder.java:459) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.DefaultClassFinder.access$200(DefaultClassFinder.java:49) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.DefaultClassFinder$InfoBuildingVisitor.extractSuperInterfaces(DefaultClassFinder.java:511) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.DefaultClassFinder$InfoBuildingVisitor.visit(DefaultClassFinder.java:498) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.1.jar:5.1]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-5.1.jar:5.1]
	at org.apache.struts2.convention.DefaultClassFinder.readClassDef(DefaultClassFinder.java:459) ~[struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.DefaultClassFinder.<init>(DefaultClassFinder.java:90) [struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.PackageBasedActionConfigBuilder.buildClassFinder(PackageBasedActionConfigBuilder.java:397) [struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.PackageBasedActionConfigBuilder.findActions(PackageBasedActionConfigBuilder.java:379) [struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.PackageBasedActionConfigBuilder.buildActionConfigs(PackageBasedActionConfigBuilder.java:335) [struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.convention.ClasspathPackageProvider.loadPackages(ClasspathPackageProvider.java:53) [struts2-convention-plugin-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.config.impl.DefaultConfiguration.reloadContainer(DefaultConfiguration.java:199) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration(ConfigurationManager.java:67) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.Dispatcher.getContainer(Dispatcher.java:906) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.Dispatcher.init_PreloadConfiguration(Dispatcher.java:445) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.Dispatcher.init(Dispatcher.java:486) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.InitOperations.initDispatcher(InitOperations.java:75) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.init(StrutsPrepareAndExecuteFilter.java:63) [struts2-core-2.5.10.1.jar:2.5.10.1]
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139) [jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:741) [jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:348) [jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501) [jetty-webapp-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463) [jetty-webapp-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261) [jetty-servlet-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) [jetty-webapp-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:453) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:564) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:239) [jetty-deploy-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.Server.start(Server.java:452) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.server.Server.doStart(Server.java:419) [jetty-server-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1511) [jetty-xml-9.4.5.v20170502.jar:9.4.5.v20170502]
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1438) [jetty-xml-9.4.5.v20170502.jar:9.4.5.v20170502]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1437) [jetty-xml-9.4.5.v20170502.jar:9.4.5.v20170502]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:531) ~[?:?]
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:221) [start.jar:9.4.5.v20170502]
	at org.eclipse.jetty.start.Main.start(Main.java:499) [start.jar:9.4.5.v20170502]
	at org.eclipse.jetty.start.Main.main(Main.java:78) [start.jar:9.4.5.v20170502]
2017-07-19 10:17:15.208:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@74455848{/,file:///home/KeyBox-jetty/jetty/keybox/,AVAILABLE}{file:///home/KeyBox-jetty/jetty//keybox}
2017-07-19 10:17:15.218:INFO:oejus.SslContextFactory:main: x509=X509@765ffb14(jetty,h=[],w=[]) for SslContextFactory@57562473(file:///home/KeyBox-jetty/jetty/etc/keystore,file:///home/KeyBox-jetty/jetty/etc/keystore)
2017-07-19 10:17:15.224:INFO:oejs.AbstractConnector:main: Started ServerConnector@39055109{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2017-07-19 10:17:15.224:INFO:oejs.Server:main: Started @11966ms
```
The above is the error I get on start of KeyBox

**Comment by varshithr** [comment]
I am running it on Ubuntu 16.04 LTS version

**Comment by skavanagh** [comment]
that seems like a Java problem. What does
```
echo $JAVA_HOME
```
and
```
 java -version
```
 show?

**Comment by skavanagh** [comment]
On Ubuntu I'm using openjdk-8-jdk
```
apt-get install openjdk-8-jdk
```

**Comment by varshithr** [comment]
Thanks for the response.

```root@campaigns:/home/KeyBox-jetty# echo $JAVA_HOME
/usr/lib/jvm/java-9-openjdk-amd64

root@campaigns:/home/KeyBox-jetty# java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

root@campaigns:/home/KeyBox-jetty#```

This is the output I get, Sean. I don't know what I am doing wrong.

**Comment by skavanagh** [comment]
Yes - It is.  I don't know if the web server supports java 9 yet.  I don't think it's in final release until Sept - http://openjdk.java.net/projects/jdk9/
