### ISSUE TITLE
EC2box AWS Credentials error

### ISSUE THREAD

**Issue by asgluser** [skavanagh/KeyBox#280]
Hello,
After configuration of EC2Box in AWS environment I am trying to add the AWS credentials: Access Key and Secret Key. But I received the error, that the credentials are invalid.
I tried it several times with different AWS credentials, but still the same error. Do you know what can be the issue of it?

![image](https://user-images.githubusercontent.com/40801992/42231165-19362e88-7eeb-11e8-973b-ad56cdf8e5c4.png)

**Comment by asgluser** [comment]
Access key is fine. It is without "*". It is masked for this question. 
As I wrote I tried several different keys for this purposes. But received the same error.  I check the policies in AWS. There is no restrictions for Keys usage. Do you have any ideas in what direction I need to dig?

**Comment by asgluser** [comment]
What permissions should have an AWS account, which keys are used?

**Comment by asgluser** [comment]
I checked the permissions for this account. It has the admin privileges and I can connect with AWS CLI using it credentials.  I suppose that it is not an account problem, because I have tried several accounts, but the result is the same, as mentioned in the first post.  What about network configuration, VPC or security groups? Are there any restrictions for such connection?

**Comment by asgluser** [comment]
Where can I find the log file? Maybe it will help to identify the problem.

**Comment by skavanagh** [comment]
If you use the AMI image they are in /opt/EC2Box/logs, otherwise they go to standard out.  If it's not able to hit the AWS APIs you should see something like so

com.amazonaws.SdkClientException: Unable to execute HTTP request: ec2.us-west-2.amazonaws.com
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
       

You may not be able to hit the APIs from inside the VPC.  You can setup a proxy for the calls here if that is an option.

https://github.com/skavanagh/EC2Box/blob/master/src/main/resources/EC2BoxConfig.properties#L44-L48

**Comment by asgluser** [comment]
I have the following errors:
Caused by: sun.security.validator.ValidatorException: No trusted certificate found
        at sun.security.validator.SimpleValidator.buildTrustedChain(java.base@9-internal/SimpleValidator.java:395)
        at sun.security.validator.SimpleValidator.engineValidate(java.base@9-internal/SimpleValidator.java:134)
        at sun.security.validator.Validator.validate(java.base@9-internal/Validator.java:271)
        at sun.security.ssl.X509TrustManagerImpl.validate(java.base@9-internal/X509TrustManagerImpl.java:343)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(java.base@9-internal/X509TrustManagerImpl.java:237)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(java.base@9-internal/X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.checkServerCerts(java.base@9-internal/ClientHandshaker.java:1820)
        ... 92 more
com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: No trusted certificate found
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:16445)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:16421)
        at com.amazonaws.services.ec2.AmazonEC2Client.executeDescribeKeyPairs(AmazonEC2Client.java:8219)
        at com.amazonaws.services.ec2.AmazonEC2Client.describeKeyPairs(AmazonEC2Client.java:8194)
        at com.amazonaws.services.ec2.AmazonEC2Client.describeKeyPairs(AmazonEC2Client.java:8231)
        at com.ec2box.manage.control.AWSCredKtrl.validateSaveAWSCred(AWSCredKtrl.java:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)

**Comment by skavanagh** [comment]
You may have outdated certs installed. What version of Java are you using?  You need 9 or greater. Also, found this if you are using the Oracle JDK

https://stackoverflow.com/a/30699960

**Comment by asgluser** [comment]
I am using the EC2Box AMI image from Amazon Marketplace.
Java version is:
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**Comment by skavanagh** [comment]
I think you hit this bug. https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/983302

Maybe when upgrading your packages. Try

$ sudo dpkg --purge --force-depends ca-certificates-java 
$ sudo apt-get install ca-certificates-java

**Comment by skavanagh** [comment]
You’ll also have to do a 

$ sudo service ec2box stop
$ sudo service ec2box start

**Comment by asgluser** [comment]
Thank you. Definitely it is helped me. Appreciated.
