### ISSUE TITLE
Unable to mirgrate to 2.82 with/ MVStore db

### ISSUE THREAD

**Issue by rgv151** [skavanagh/KeyBox#72]
my keybox version 2.76.00 is running with a keybox.mv.db file, now I can't upgrade it to latest version w/ keybox-upgrade tool.

**Output of keybox-upgrade-2_80.jar:**
Upgrade failed
org.h2.jdbc.JdbcSQLException: Table "USERS" not found; SQL statement:
alter table users add auth_type varchar not null default 'BASIC' [42102-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.Parser.readTableOrView(Parser.java:4900)
	at org.h2.command.Parser.readTableOrView(Parser.java:4878)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4951)
	at org.h2.command.Parser.parseAlter(Parser.java:4412)
	at org.h2.command.Parser.parsePrepared(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.parse(Parser.java:261)
	at org.h2.command.Parser.prepareCommand(Parser.java:226)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at Upgrade.main(Upgrade.java:33)

**Output of keybox-upgrade-2_82.jar:**
Upgrade failed
org.h2.jdbc.JdbcSQLException: Table "TERMINAL_LOG" not found; SQL statement:
alter table terminal_log add instance_id INTEGER [42102-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.Parser.readTableOrView(Parser.java:4900)
	at org.h2.command.Parser.readTableOrView(Parser.java:4878)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4951)
	at org.h2.command.Parser.parseAlter(Parser.java:4412)
	at org.h2.command.Parser.parsePrepared(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.parse(Parser.java:261)
	at org.h2.command.Parser.prepareCommand(Parser.java:226)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at Upgrade.main(Upgrade.java:33)

**Comment by skavanagh** [comment]
Huh.. the upgrade tool is using keybox.h2.db. Try renaming keybox.mv.db to keybox.h2.db and run again. If it doesn't work I'll try and modify the upgrade jars to look for both.

**Comment by skavanagh** [comment]
Renaming won't work!  The problem is the upgrade tools are using an older h2 driver that doesn't support MVStore.  I'll update them tonight

**Comment by rgv151** [comment]
yup, I tried but no luck. thank you so much!

-----
Best regards.
Huy Doan (aka Bruce)

**Comment by skavanagh** [comment]
Updated keybox-upgrade-2_80.jar and keybox-upgrade-2_82.jar to use the new h2 driver so it should work with the MVStore DB.

**Comment by rgv151** [comment]
sounds great, previous version worked for me too, thank you!

-----
Best regards.
Huy Doan (aka Bruce)
